name: Build Wheel

on:
  workflow_dispatch:

  push:
    branches: [ "Cross_platform", "Build_in_Manylinux_image" ]

  pull_request:
    branches: [ "Cross_platform", "Build_in_Manylinux_image" ]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: yum install -y zip ninja-build

      - run: |
          git clone --depth=1 http://www.github.com/Microsoft/vcpkg
          cd vcpkg
          ./bootstrap-vcpkg.sh
          export VCPKG_INSTALLATION_ROOT=vcpkg

      - run: ls .

      - run: ls sDNA/

      - run: ls sDNA/geos/
        
      - run: ls sDNA/geos/x64

      - run: ls sDNA/geos/x64/src

      - run: |
          curl -OL http://download.osgeo.org/geos/geos-3.3.5.tar.bz2
          tar xfj geos-3.3.5.tar.bz2
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build_geos/_installed -DBUILD_SHARED_LIBS=ON -DBUILD_DOCUMENTATION=OFF -DBUILD_TESTING=OFF -G Ninja -B build_geos -S geos-3.3.5
          cmake --build build_geos
          cp build_geos/lib/libgeos_c.so sDNA/geos/x64/src

      - run: |
          export PATH=/opt/python/cp312-cp312/bin/:$PATH
          python -m venv venv
          . venv/bin/activate
          python -m pip install build hatchling hatch-requirements-txt
          python -m build --no-isolation --wheel

      - name: upload_output
        id: installer-upload-step
        uses: actions/upload-artifact@v3
        with:
          name: python_wheel_gcc_linux
          path: dist