name: "Compile with MSBuild and VS 2022 for Windows"

on:
  workflow_dispatch:
  push:
    branches: [ "VS_2022_x64_release_config_only" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: sDNA\sdna_vs2008\sdna_vs2008.sln
  CONFIGURATION: Release
  PLATFORM: x64
  OSGEO4W_GEOS_URL: https://download.osgeo.org/osgeo4w/v2/x86_64/release/geos
  GEOS_VERSION: '3.12.0-1'
  GEOS_DOWNLOAD_DIR: ${{ runner.temp }}/geos
  RELEASE: '6.0.1'
  RELEASE_ZIP_FILES_DIR: ${{ runner.temp }}/release_files
  BOOST_VERSION: '1.8.3'

jobs:
  compile:
    name: Try to compile on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4




    - name: 'Add "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\bin" to path'
      shell: bash
      run: echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\bin" >> $GITHUB_PATH

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Integrate vcpkg with Visual Studio
      run: vcpkg integrate install


    - name: Restore Cache'd Geos binary
      id: cache-geos-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ${{ github.workspace }}\output\${{ env.CONFIGURATION }}\${{ env.PLATFORM }}\geos_c.dll
        key: ${{ runner.os }}-geos_v${{ env.GEOS_VERSION }}

    - name: Download and unzip Geos binary from OSGEO
      if: steps.cache-geos-restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        GEOS_FILE=geos-${{ env.GEOS_VERSION }}.tar.bz2
        mkdir ${{ env.GEOS_DOWNLOAD_DIR }}
        cd ${{ env.GEOS_DOWNLOAD_DIR }}
        curl -L -o $GEOS_FILE ${{ env.OSGEO4W_GEOS_URL }}/$GEOS_FILE
        tar -xf $GEOS_FILE
        BUILD_CONFIG=${{ env.CONFIGURATION }}
        mv bin/geos_c.dll $GITHUB_WORKSPACE/output/${BUILD_CONFIG,R}/${{ env.PLATFORM }}
      # ${BUILD_CONFIG,R} Tries to make first letter of BUILD_CONFIG lowercase only if it is an R
      # as the sDNA source tree has output/Debug
      #                             output/release

    - name: Cache Geos binary
      if: steps.cache-geos-restore.outputs.cache-hit != 'true'
      id: cache-geos-save
      uses: actions/cache/save@v3
      with:
        path: |
          ${{ github.workspace }}\output\${{ env.CONFIGURATION }}\${{ env.PLATFORM }}\geos_c.dll
        key: ${{ steps.cache-geos-restore.outputs.cache-primary-key }}

    - name: Restore vcpkg Deps
      id: cache-vcpkg-deps-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          C:\vcpkg\packages\
          D:\a\sdna_plus\sdna_plus\vcpkg_installed\
        key: ${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

    # Let vcpkg do its thing with the cache and don't skip this step
    # is there is a cache hit - vcpkg will detect pre existing files.
    - name: Install Boost from vcpkg.json
      run: vcpkg install


    - name: Cache vcpkg Deps
      if: steps.cache-vcpkg-deps-restore.outputs.cache-hit != 'true'
      id: cache-deps-save
      uses: actions/cache/save@v3
      with:
        path: |
          C:\vcpkg\packages\
          D:\a\sdna_plus\sdna_plus\vcpkg_installed\
        key: ${{ steps.cache-vcpkg-deps-restore.outputs.cache-primary-key }}


    - name: Build sDNA
      working-directory: ${{ github.workspace }}
      # run: msbuild /m  /p:VcpkgEnableManifest=true ${{env.SOLUTION_FILE_PATH}}
      run: > 
        msbuild build_installer.proj 
        /t:rebuild 
        /p:Platform=${{ env.PLATFORM }}  
        /p:Configuration=${{ env.CONFIGURATION }} 
        /p:VcpkgEnableManifest=true

    - name: Package sDNA
      shell: bash
      run: |
        mkdir -p ${{ env.RELEASE_ZIP_FILES_DIR }}
        RELEASE_FILE_NAME=sDNA_lite_v${{ env.RELEASE }}_${{ env.PLATFORM }}_${{ env.CONFIGURATION }}_osgeo4w_geos_v${{ env.GEOS_VERSION }}_Boost_v${{ env.BOOST_VERSION }}_RTTI_on
        RELEASE_FILE_NAME_STUB_AND_DIR=${{ env.RELEASE_ZIP_FILES_DIR }}/%RELEASE_FILE_NAME%
        BUILD_CONFIG=${{ env.CONFIGURATION }}

        cd output/${BUILD_CONFIG,R}
        tar -acf $RELEASE_FILE_NAME_STUB_AND_DIR.zip *
        tar -cjf $RELEASE_FILE_NAME_STUB_AND_DIR.tar.bz2 *

    - name: upload output dir
      uses: actions/upload-artifact@v3
      with:
        name: sdna_plus_output
        # path: output/release
        path: ${{ env.RELEASE_ZIP_FILES_DIR }}


