on:
  workflow_dispatch:

jobs:
  compile:
    name: Try to compile on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Add "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\bin" to path'
      shell: bash
      run: echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\bin" >> $GITHUB_PATH
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      # https://github.com/microsoft/setup-msbuild
    - name: Build Geos
      shell: cmd
      run: sDNA\geos\build_in_ci_vs_2022.bat
    - name: Run MSBuild on main sdna_plus .proj
      shell: cmd 
      run:  MSBuild.exe build_installer.proj /t:rebuild /p:Configuration=release'
    - name: upload output dir
      uses: actions/upload-artifact@v3
      with:
        name: sdna_plus_output
        path: output/
        retention-days: 5