name: run_diff_tests

on:

  # workflow_dispatch:

  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: "3.12.2"



jobs:




  run_diff_tests:
    name: "Run the diff tests, with pytest. "
    
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4


    - uses: LizardByte/setup-python-action@master
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install Pytest, and Numpy (the latter for sDNA Learn & Predict).
      working-directory: .\sDNA\sdna_vs2008\tests\pytest
      run: pip install pytest numpy

    - name: Show versions.
      working-directory: '.\sDNA\sdna_vs2008\tests\pytest'
      run: |
        python --version
        python -c "import numpy; print('Numpy: %s' % numpy.__version__)"
        python -m pytest --version

    - name: Run the diff tests with Pytest.
      # TODO: This is an unrepresentative test under the 
      # default values, when called from
      # test_an_msi_from_the_releases_page.yml.  As the 
      # sdna_vs2008.dll binary
      # being tested is from the releases downloads page, but the sDNA Python
      # glue code being tested, is from the source code repo.
    
      # For the current question (of formally supporting Python 3, as well 
      # as Python 2), this is fine until the C++ code is changed.  But should be
      # addressed before this testing approach is relied on further.  
      # 
      # The test
      # directory probably just needs to be copied from the repo, into the sDNA
      # installation to be tested's tree, and pytest run from there.  
    
      working-directory: .\sdna_plus\sDNA\sdna_vs2008\tests\pytest
      run: pytest -rA
      # -rA shows summary of tests, one per line, even when they all pass.
