name: "Smoke test (GCC)."

on:
  workflow_dispatch:

  push:
    branches: [ "Test_using_so_on_Linux", "Cross_platform"]

  pull_request:
    branches: [ "Test_using_so_on_Linux", "Cross_platform"]

env:
  CONFIGURATION: Release
  PLATFORM: x64
  BOOST_VERSION: '1.8.3'


jobs:
  build_and_upload_installer:
    name: "Compile on Ubuntu with CMake & GCC"
    runs-on: "ubuntu-24.04"
    # outputs:
    #   installer_file_name: ${{ steps.output_installer_file_name.outputs.name }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git ninja-build

    - name: Create Ninja build system from CMake
      run: >
        cmake
        -G "Ninja Multi-Config"
        -D USE_ZIG=OFF
        -B build_output_cmake_gcc
        -S .
        
    - name: Build sDNA
      run: |
        cmake --build build_output_cmake_gcc --config Release



    - name: upload_output
      id: installer-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: output_gcc_linux
        path: output


  test_installer:

    needs: build_and_upload_installer

    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.11']
        smoke_test: ["debug_test.py",
                      "hybrid_test.py",
                      "3d_test.py",
                      "partial_test.py",
                      "test_parallel_results.py",
                      "prepare_barns_test.py" ]

    name: "Download and run sDNA installer, and run diff tests on it. "
    
    runs-on: "ubuntu-24.04"


    steps:


    - uses: actions/checkout@v4

    - uses: LizardByte/setup-python-action@master
      with:
        python-version: ${{ matrix.python_version }}

    - name: Download output tree built in previous job
      uses: actions/download-artifact@v4
      with:
        name: output_gcc_linux
        path: output

    - name: Smoke test
      working-directory: ./sDNA/sdna_vs2008/tests
      env:
        sdnadll: '${{ github.workspace }}/output/Release/x64/sdna_vs2008.so'
      run: "python -u ${{ matrix.smoke_test }}"
