name: test_an_msi_from_the_releases_page

on:
  workflow_call:
    inputs:
      VERSION: 
        type: string
        required: false 
        default: 4_1_1

      DOWNLOAD_URL_PREFIX:
        type: string
        required: false
        default: https://sdna.cardiff.ac.uk/sdna/wp-content/downloads/sDNA_setup_win_v
    #      e.g.: https://sdna.cardiff.ac.uk/sdna/wp-content/downloads/sDNA_setup_win_v4_1_1.msi
    #            https://sdna.cardiff.ac.uk/sdna/wp-content/downloads/old%20versions/sDNA_setup_win_v3_4_5.msi
  workflow_dispatch:
    





jobs:

  download_and_install_sDNA_msi:
    name: "Download and install a release of sDNA. "
    
    runs-on: windows-2022
    # Note:  The Windows server 2022 Github runner image already includes  
    # Python (currently 6 versions from 3.7 to 3.12) and a couple of 
    # VC++ redistributables.  Desktop users may need to install these 
    # themselves, in addition to sDNA.      
    #
    # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    #
    # The test code this action calls (run_diff_tests.yml) installs the 
    # specified version of Python, and the dep for sDNA Learn (numpy), 
    # and Pytest. 
    steps:
    - name: Download and install release of sDNA, then delete installer file.
      run: |
        Invoke-WebRequest ${{ inputs.DOWNLOAD_URL_PREFIX }}${{ inputs.VERSION }}.msi -OutFile sDNA_setup_win_v${{ inputs.SDNA_VERSION }}.msi
        .\sDNA_setup_win_v${{ inputs.VERSION }}.msi /passive
        Remove-Item .\sDNA_setup_win_v${{ inputs.VERSION }}.msi

  test_sDNA_msi:
    strategy:
      matrix:
        # full version triplet needed for pyenv-win
        python_version: ['3.12.2', '2.7.18']
    name: "Run diff_tests.yml on the installed sDNA release"
    uses: ./.github/workflows/diff_tests.yml
