name: test_an_msi_from_the_releases_page

on:  
  push:
    branches: ["Test_releases_in_a_Github_Action"]
  workflow_call:

  workflow_dispatch:
    

env:
  VERSION: 4_1_1

  DOWNLOAD_URL_PREFIX: https://sdna.cardiff.ac.uk/sdna/wp-content/downloads/sDNA_setup_win_v
#                e.g.: https://sdna.cardiff.ac.uk/sdna/wp-content/downloads/sDNA_setup_win_v4_1_1.msi
#                      https://sdna.cardiff.ac.uk/sdna/wp-content/downloads/old%20versions/sDNA_setup_win_v3_4_5.msi



jobs:

  download_and_install_sDNA_msi:
    name: "Download and install a release of sDNA. "
    
    runs-on: windows-2022
    # Note:  The Windows server 2022 Github runner image already includes  
    # Python (currently 6 versions from 3.7 to 3.12) and a couple of 
    # VC++ redistributables.  Desktop users may need to install these 
    # themselves, in addition to sDNA.      
    #
    # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    #
    # The test code this action calls (run_diff_tests.yml) installs the 
    # specified version of Python, and the dep for sDNA Learn (numpy), 
    # and Pytest. 
    steps:
    - name: Download and install release of sDNA, then delete installer file.
      run: |
        Invoke-WebRequest ${{ env.DOWNLOAD_URL_PREFIX }}${{ env.VERSION }}.msi -OutFile sDNA_setup_win_v${{ env.VERSION }}.msi
        .\sDNA_setup_win_v${{ env.VERSION }}.msi /passive
        Remove-Item .\sDNA_setup_win_v${{ env.VERSION }}.msi


    - name: List dir
      run: dir d:\a\

    - name: dir sdna
      working-directory: 'd:'
      shell: cmd
      run: dir d:\a\sdna_plus\

    - name: dir sdna\sdna
      working-directory: 'd:'
      shell: cmd
      run: dir d:\a\sdna_plus\sdna_plus

    - name: Echo path 
      shell: cmd
      run: echo %path%


    - name: List c:\
      run: 'dir "C:\"'

    - name: List Program Files
      run: 'dir "C:\Program Files\"'


  # test_sDNA_msi:
  

  #   needs: download_and_install_sDNA_msi
  #     # TODO: This is an unrepresentative test. As the 
  #     # sdna_vs2008.dll binary
  #     # being tested is from the releases downloads page, but the sDNA Python
  #     # glue code being tested, is from the source code repo.
    
  #     # For the current question (of formally supporting Python 3, as well 
  #     # as Python 2), this is fine until the C++ code is changed.  But should be
  #     # addressed before this testing approach is relied on further.  
  #     # 
  #     # The test
  #     # directory probably just needs to be copied from the repo, into the sDNA
  #     # installation to be tested's tree, and pytest run from there.  
  #   strategy:
  #     matrix:
  #       python_version: ['3.12'] #, '2.7']
  #       test_index: [0]
  #   name: "Run diff_tests.yml on the installed sDNA release"
  #   uses: ./.github/workflows/diff_tests.yml
  #   with:
  #     python_version: ${{ matrix.python_version }}
  #     test_index: ${{ matrix.test_index }}
